# Generated by Django 5.0.6 on 2024-06-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('client', 'Заказчик')], max_length=20, verbose_name='Роль'),
        ),
    ]
