# Generated by Django 5.0.6 on 2024-06-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('client', 'Заказчик')], max_length=20, verbose_name='Роль'),
        ),
    ]
