version: '3'

services:
  service_task:
    container_name: service
    restart: always
    build: .

    command: bash -c "python3 manage.py migrate && python3 manage.py runserver"

    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}

    env_file: .env

    ports:
      - 8000:8000