# Generated by Django 5.0.6 on 2024-06-25 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('status', models.CharField(choices=[('pending', 'Ожидает исполнителя'), ('in_progress', 'В процессе'), ('completed', 'Выполнена')], default='pending', max_length=20, verbose_name='Статус')),
                ('report', models.TextField(blank=True, verbose_name='Отчёт')),
            ],
        ),
    ]
