# Generated by Django 5.0.6 on 2024-06-26 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_delete_user'),
        ('task', '0002_alter_task_client_alter_task_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_task', to='accounts.users', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_task', to='accounts.users', verbose_name='Сотрудник'),
        ),
    ]
